version: "3"
services:
  node:
    image: "node:lts"
    cpus: 4
    working_dir: /src
    environment:
      - YARN_CACHE_FOLDER=/.cache/yarn_cache_folder
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - ../:/src
      - ./:/docker
      - cache:/.cache
    command: ["/docker/node-entrypoint.sh"]
  go:
    image: "golang"
    depends_on: 
      - "node"
    working_dir: /
    environment:
      - GOCACHE=/.cache/gocache
    volumes:
      - ../:/src
      - ./:/docker
      - cache:/.cache
    entrypoint: ["/docker/go-entrypoint.sh"]
volumes:
  cache: